### ISSUE TITLE
第一周作业

### ISSUE THREAD

**Issue by liruidong1** [algorithm011-class01/algorithm011-class01#10]
#学号: G20200447020213
#姓名: 李瑞东
#班级: 11期1班
#语言: Typescript
#作业链接: https://github.com/liruidong1/algorithm011-class01/tree/master/Week_01
#总结链接: https://github.com/liruidong1/algorithm011-class01/tree/master/Week_01

**Comment by biaderbia** [comment]
#学号: G20200343080303
#姓名: 刘雪刚
#班级: 11期1班
#语言: Java
#作业链接: https://github.com/biaderbia/algorithm011-class01/tree/master/Week_01
#总结链接: https://github.com/biaderbia/algorithm011-class01/tree/master/Week_01
